use crate::processor::instructions::{Instruction, OpCode, Operand};
pub const UNPREFIXED: [Instruction; 256] = [
    Instruction::new(OpCode::Nop, &[], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::BC, Operand::N16], 12, 3),
    Instruction::new(OpCode::Ld, &[Operand::BCPointer, Operand::A], 8, 1),
    Instruction::new(OpCode::Inc, &[Operand::BC], 8, 1),
    Instruction::new(OpCode::Inc, &[Operand::B], 4, 1),
    Instruction::new(OpCode::Dec, &[Operand::B], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::B, Operand::N8], 8, 2),
    Instruction::new(OpCode::Rlca, &[], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::A16Pointer, Operand::SP], 20, 3),
    Instruction::new(OpCode::Add, &[Operand::HL, Operand::BC], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::BCPointer], 8, 1),
    Instruction::new(OpCode::Dec, &[Operand::BC], 8, 1),
    Instruction::new(OpCode::Inc, &[Operand::C], 4, 1),
    Instruction::new(OpCode::Dec, &[Operand::C], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::C, Operand::N8], 8, 2),
    Instruction::new(OpCode::Rrca, &[], 4, 1),
    Instruction::new(OpCode::Stop, &[Operand::N8], 4, 2),
    Instruction::new(OpCode::Ld, &[Operand::DE, Operand::N16], 12, 3),
    Instruction::new(OpCode::Ld, &[Operand::DEPointer, Operand::A], 8, 1),
    Instruction::new(OpCode::Inc, &[Operand::DE], 8, 1),
    Instruction::new(OpCode::Inc, &[Operand::D], 4, 1),
    Instruction::new(OpCode::Dec, &[Operand::D], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::D, Operand::N8], 8, 2),
    Instruction::new(OpCode::Rla, &[], 4, 1),
    Instruction::new(OpCode::Jr, &[Operand::E8], 12, 2),
    Instruction::new(OpCode::Add, &[Operand::HL, Operand::DE], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::DEPointer], 8, 1),
    Instruction::new(OpCode::Dec, &[Operand::DE], 8, 1),
    Instruction::new(OpCode::Inc, &[Operand::E], 4, 1),
    Instruction::new(OpCode::Dec, &[Operand::E], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::E, Operand::N8], 8, 2),
    Instruction::new(OpCode::Rra, &[], 4, 1),
    Instruction::new(OpCode::Jr, &[Operand::NotZero, Operand::E8], 8, 2),
    Instruction::new(OpCode::Ld, &[Operand::HL, Operand::N16], 12, 3),
    Instruction::new(OpCode::Ld, &[Operand::HLI, Operand::A], 8, 1),
    Instruction::new(OpCode::Inc, &[Operand::HL], 8, 1),
    Instruction::new(OpCode::Inc, &[Operand::H], 4, 1),
    Instruction::new(OpCode::Dec, &[Operand::H], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::H, Operand::N8], 8, 2),
    Instruction::new(OpCode::Daa, &[], 4, 1),
    Instruction::new(OpCode::Jr, &[Operand::Zero, Operand::E8], 8, 2),
    Instruction::new(OpCode::Add, &[Operand::HL, Operand::HL], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::HLI], 8, 1),
    Instruction::new(OpCode::Dec, &[Operand::HL], 8, 1),
    Instruction::new(OpCode::Inc, &[Operand::L], 4, 1),
    Instruction::new(OpCode::Dec, &[Operand::L], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::L, Operand::N8], 8, 2),
    Instruction::new(OpCode::Cpl, &[], 4, 1),
    Instruction::new(OpCode::Jr, &[Operand::NotCarry, Operand::E8], 8, 2),
    Instruction::new(OpCode::Ld, &[Operand::SP, Operand::N16], 12, 3),
    Instruction::new(OpCode::Ld, &[Operand::HLD, Operand::A], 8, 1),
    Instruction::new(OpCode::Inc, &[Operand::SP], 8, 1),
    Instruction::new(OpCode::Inc, &[Operand::HLPointer], 12, 1),
    Instruction::new(OpCode::Dec, &[Operand::HLPointer], 12, 1),
    Instruction::new(OpCode::Ld, &[Operand::HLPointer, Operand::N8], 12, 2),
    Instruction::new(OpCode::Scf, &[], 4, 1),
    Instruction::new(OpCode::Jr, &[Operand::Carry, Operand::E8], 8, 2),
    Instruction::new(OpCode::Add, &[Operand::HL, Operand::SP], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::HLD], 8, 1),
    Instruction::new(OpCode::Dec, &[Operand::SP], 8, 1),
    Instruction::new(OpCode::Inc, &[Operand::A], 4, 1),
    Instruction::new(OpCode::Dec, &[Operand::A], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::N8], 8, 2),
    Instruction::new(OpCode::Ccf, &[], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::B, Operand::B], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::B, Operand::C], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::B, Operand::D], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::B, Operand::E], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::B, Operand::H], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::B, Operand::L], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::B, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::B, Operand::A], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::C, Operand::B], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::C, Operand::C], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::C, Operand::D], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::C, Operand::E], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::C, Operand::H], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::C, Operand::L], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::C, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::C, Operand::A], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::D, Operand::B], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::D, Operand::C], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::D, Operand::D], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::D, Operand::E], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::D, Operand::H], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::D, Operand::L], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::D, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::D, Operand::A], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::E, Operand::B], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::E, Operand::C], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::E, Operand::D], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::E, Operand::E], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::E, Operand::H], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::E, Operand::L], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::E, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::E, Operand::A], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::H, Operand::B], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::H, Operand::C], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::H, Operand::D], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::H, Operand::E], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::H, Operand::H], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::H, Operand::L], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::H, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::H, Operand::A], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::L, Operand::B], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::L, Operand::C], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::L, Operand::D], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::L, Operand::E], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::L, Operand::H], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::L, Operand::L], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::L, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::L, Operand::A], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::HLPointer, Operand::B], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::HLPointer, Operand::C], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::HLPointer, Operand::D], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::HLPointer, Operand::E], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::HLPointer, Operand::H], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::HLPointer, Operand::L], 8, 1),
    Instruction::new(OpCode::Halt, &[], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::HLPointer, Operand::A], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::B], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::C], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::D], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::E], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::H], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::L], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::A], 4, 1),
    Instruction::new(OpCode::Add, &[Operand::A, Operand::B], 4, 1),
    Instruction::new(OpCode::Add, &[Operand::A, Operand::C], 4, 1),
    Instruction::new(OpCode::Add, &[Operand::A, Operand::D], 4, 1),
    Instruction::new(OpCode::Add, &[Operand::A, Operand::E], 4, 1),
    Instruction::new(OpCode::Add, &[Operand::A, Operand::H], 4, 1),
    Instruction::new(OpCode::Add, &[Operand::A, Operand::L], 4, 1),
    Instruction::new(OpCode::Add, &[Operand::A, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Add, &[Operand::A, Operand::A], 4, 1),
    Instruction::new(OpCode::Adc, &[Operand::A, Operand::B], 4, 1),
    Instruction::new(OpCode::Adc, &[Operand::A, Operand::C], 4, 1),
    Instruction::new(OpCode::Adc, &[Operand::A, Operand::D], 4, 1),
    Instruction::new(OpCode::Adc, &[Operand::A, Operand::E], 4, 1),
    Instruction::new(OpCode::Adc, &[Operand::A, Operand::H], 4, 1),
    Instruction::new(OpCode::Adc, &[Operand::A, Operand::L], 4, 1),
    Instruction::new(OpCode::Adc, &[Operand::A, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Adc, &[Operand::A, Operand::A], 4, 1),
    Instruction::new(OpCode::Sub, &[Operand::A, Operand::B], 4, 1),
    Instruction::new(OpCode::Sub, &[Operand::A, Operand::C], 4, 1),
    Instruction::new(OpCode::Sub, &[Operand::A, Operand::D], 4, 1),
    Instruction::new(OpCode::Sub, &[Operand::A, Operand::E], 4, 1),
    Instruction::new(OpCode::Sub, &[Operand::A, Operand::H], 4, 1),
    Instruction::new(OpCode::Sub, &[Operand::A, Operand::L], 4, 1),
    Instruction::new(OpCode::Sub, &[Operand::A, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Sub, &[Operand::A, Operand::A], 4, 1),
    Instruction::new(OpCode::Sbc, &[Operand::A, Operand::B], 4, 1),
    Instruction::new(OpCode::Sbc, &[Operand::A, Operand::C], 4, 1),
    Instruction::new(OpCode::Sbc, &[Operand::A, Operand::D], 4, 1),
    Instruction::new(OpCode::Sbc, &[Operand::A, Operand::E], 4, 1),
    Instruction::new(OpCode::Sbc, &[Operand::A, Operand::H], 4, 1),
    Instruction::new(OpCode::Sbc, &[Operand::A, Operand::L], 4, 1),
    Instruction::new(OpCode::Sbc, &[Operand::A, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Sbc, &[Operand::A, Operand::A], 4, 1),
    Instruction::new(OpCode::And, &[Operand::A, Operand::B], 4, 1),
    Instruction::new(OpCode::And, &[Operand::A, Operand::C], 4, 1),
    Instruction::new(OpCode::And, &[Operand::A, Operand::D], 4, 1),
    Instruction::new(OpCode::And, &[Operand::A, Operand::E], 4, 1),
    Instruction::new(OpCode::And, &[Operand::A, Operand::H], 4, 1),
    Instruction::new(OpCode::And, &[Operand::A, Operand::L], 4, 1),
    Instruction::new(OpCode::And, &[Operand::A, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::And, &[Operand::A, Operand::A], 4, 1),
    Instruction::new(OpCode::Xor, &[Operand::A, Operand::B], 4, 1),
    Instruction::new(OpCode::Xor, &[Operand::A, Operand::C], 4, 1),
    Instruction::new(OpCode::Xor, &[Operand::A, Operand::D], 4, 1),
    Instruction::new(OpCode::Xor, &[Operand::A, Operand::E], 4, 1),
    Instruction::new(OpCode::Xor, &[Operand::A, Operand::H], 4, 1),
    Instruction::new(OpCode::Xor, &[Operand::A, Operand::L], 4, 1),
    Instruction::new(OpCode::Xor, &[Operand::A, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Xor, &[Operand::A, Operand::A], 4, 1),
    Instruction::new(OpCode::Or, &[Operand::A, Operand::B], 4, 1),
    Instruction::new(OpCode::Or, &[Operand::A, Operand::C], 4, 1),
    Instruction::new(OpCode::Or, &[Operand::A, Operand::D], 4, 1),
    Instruction::new(OpCode::Or, &[Operand::A, Operand::E], 4, 1),
    Instruction::new(OpCode::Or, &[Operand::A, Operand::H], 4, 1),
    Instruction::new(OpCode::Or, &[Operand::A, Operand::L], 4, 1),
    Instruction::new(OpCode::Or, &[Operand::A, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Or, &[Operand::A, Operand::A], 4, 1),
    Instruction::new(OpCode::Cp, &[Operand::A, Operand::B], 4, 1),
    Instruction::new(OpCode::Cp, &[Operand::A, Operand::C], 4, 1),
    Instruction::new(OpCode::Cp, &[Operand::A, Operand::D], 4, 1),
    Instruction::new(OpCode::Cp, &[Operand::A, Operand::E], 4, 1),
    Instruction::new(OpCode::Cp, &[Operand::A, Operand::H], 4, 1),
    Instruction::new(OpCode::Cp, &[Operand::A, Operand::L], 4, 1),
    Instruction::new(OpCode::Cp, &[Operand::A, Operand::HLPointer], 8, 1),
    Instruction::new(OpCode::Cp, &[Operand::A, Operand::A], 4, 1),
    Instruction::new(OpCode::Ret, &[Operand::NotZero], 8, 1),
    Instruction::new(OpCode::Pop, &[Operand::BC], 12, 1),
    Instruction::new(OpCode::Jp, &[Operand::NotZero, Operand::A16], 12, 3),
    Instruction::new(OpCode::Jp, &[Operand::A16], 16, 3),
    Instruction::new(OpCode::Call, &[Operand::NotZero, Operand::A16], 12, 3),
    Instruction::new(OpCode::Push, &[Operand::BC], 16, 1),
    Instruction::new(OpCode::Add, &[Operand::A, Operand::N8], 8, 2),
    Instruction::new(OpCode::Rst, &[Operand::Immediate(0x00)], 16, 1),
    Instruction::new(OpCode::Ret, &[Operand::Zero], 8, 1),
    Instruction::new(OpCode::Ret, &[], 16, 1),
    Instruction::new(OpCode::Jp, &[Operand::Zero, Operand::A16], 12, 3),
    Instruction::new(OpCode::Prefix, &[], 4, 1),
    Instruction::new(OpCode::Call, &[Operand::Zero, Operand::A16], 12, 3),
    Instruction::new(OpCode::Call, &[Operand::A16], 24, 3),
    Instruction::new(OpCode::Adc, &[Operand::A, Operand::N8], 8, 2),
    Instruction::new(OpCode::Rst, &[Operand::Immediate(0x08)], 16, 1),
    Instruction::new(OpCode::Ret, &[Operand::NotCarry], 8, 1),
    Instruction::new(OpCode::Pop, &[Operand::DE], 12, 1),
    Instruction::new(OpCode::Jp, &[Operand::NotCarry, Operand::A16], 12, 3),
    Instruction::new(OpCode::Illegal, &[], 4, 1),
    Instruction::new(OpCode::Call, &[Operand::NotCarry, Operand::A16], 12, 3),
    Instruction::new(OpCode::Push, &[Operand::DE], 16, 1),
    Instruction::new(OpCode::Sub, &[Operand::A, Operand::N8], 8, 2),
    Instruction::new(OpCode::Rst, &[Operand::Immediate(0x10)], 16, 1),
    Instruction::new(OpCode::Ret, &[Operand::Carry], 8, 1),
    Instruction::new(OpCode::Reti, &[], 16, 1),
    Instruction::new(OpCode::Jp, &[Operand::Carry, Operand::A16], 12, 3),
    Instruction::new(OpCode::Illegal, &[], 4, 1),
    Instruction::new(OpCode::Call, &[Operand::Carry, Operand::A16], 12, 3),
    Instruction::new(OpCode::Illegal, &[], 4, 1),
    Instruction::new(OpCode::Sbc, &[Operand::A, Operand::N8], 8, 2),
    Instruction::new(OpCode::Rst, &[Operand::Immediate(0x18)], 16, 1),
    Instruction::new(OpCode::Ldh, &[Operand::FF00OffsetByA8, Operand::A], 12, 2),
    Instruction::new(OpCode::Pop, &[Operand::HL], 12, 1),
    Instruction::new(OpCode::Ldh, &[Operand::FF00OffsetByC, Operand::A], 8, 1),
    Instruction::new(OpCode::Illegal, &[], 4, 1),
    Instruction::new(OpCode::Illegal, &[], 4, 1),
    Instruction::new(OpCode::Push, &[Operand::HL], 16, 1),
    Instruction::new(OpCode::And, &[Operand::A, Operand::N8], 8, 2),
    Instruction::new(OpCode::Rst, &[Operand::Immediate(0x20)], 16, 1),
    Instruction::new(OpCode::Add, &[Operand::SP, Operand::E8], 16, 2),
    Instruction::new(OpCode::Jp, &[Operand::HL], 4, 1),
    Instruction::new(OpCode::Ld, &[Operand::A16Pointer, Operand::A], 16, 3),
    Instruction::new(OpCode::Illegal, &[], 4, 1),
    Instruction::new(OpCode::Illegal, &[], 4, 1),
    Instruction::new(OpCode::Illegal, &[], 4, 1),
    Instruction::new(OpCode::Xor, &[Operand::A, Operand::N8], 8, 2),
    Instruction::new(OpCode::Rst, &[Operand::Immediate(0x28)], 16, 1),
    Instruction::new(OpCode::Ldh, &[Operand::A, Operand::FF00OffsetByA8], 12, 2),
    Instruction::new(OpCode::Pop, &[Operand::AF], 12, 1),
    Instruction::new(OpCode::Ldh, &[Operand::A, Operand::FF00OffsetByC], 8, 1),
    Instruction::new(OpCode::Di, &[], 4, 1),
    Instruction::new(OpCode::Illegal, &[], 4, 1),
    Instruction::new(OpCode::Push, &[Operand::AF], 16, 1),
    Instruction::new(OpCode::Or, &[Operand::A, Operand::N8], 8, 2),
    Instruction::new(OpCode::Rst, &[Operand::Immediate(0x30)], 16, 1),
    Instruction::new(OpCode::Ld, &[Operand::HL, Operand::SP, Operand::E8], 12, 2),
    Instruction::new(OpCode::Ld, &[Operand::SP, Operand::HL], 8, 1),
    Instruction::new(OpCode::Ld, &[Operand::A, Operand::A16Pointer], 16, 3),
    Instruction::new(OpCode::Ei, &[], 4, 1),
    Instruction::new(OpCode::Illegal, &[], 4, 1),
    Instruction::new(OpCode::Illegal, &[], 4, 1),
    Instruction::new(OpCode::Cp, &[Operand::A, Operand::N8], 8, 2),
    Instruction::new(OpCode::Rst, &[Operand::Immediate(0x38)], 16, 1),
];
pub const CBPREFIXED: [Instruction; 256] = [
    Instruction::new(OpCode::Rlc, &[Operand::B], 8, 2),
    Instruction::new(OpCode::Rlc, &[Operand::C], 8, 2),
    Instruction::new(OpCode::Rlc, &[Operand::D], 8, 2),
    Instruction::new(OpCode::Rlc, &[Operand::E], 8, 2),
    Instruction::new(OpCode::Rlc, &[Operand::H], 8, 2),
    Instruction::new(OpCode::Rlc, &[Operand::L], 8, 2),
    Instruction::new(OpCode::Rlc, &[Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Rlc, &[Operand::A], 8, 2),
    Instruction::new(OpCode::Rrc, &[Operand::B], 8, 2),
    Instruction::new(OpCode::Rrc, &[Operand::C], 8, 2),
    Instruction::new(OpCode::Rrc, &[Operand::D], 8, 2),
    Instruction::new(OpCode::Rrc, &[Operand::E], 8, 2),
    Instruction::new(OpCode::Rrc, &[Operand::H], 8, 2),
    Instruction::new(OpCode::Rrc, &[Operand::L], 8, 2),
    Instruction::new(OpCode::Rrc, &[Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Rrc, &[Operand::A], 8, 2),
    Instruction::new(OpCode::Rl, &[Operand::B], 8, 2),
    Instruction::new(OpCode::Rl, &[Operand::C], 8, 2),
    Instruction::new(OpCode::Rl, &[Operand::D], 8, 2),
    Instruction::new(OpCode::Rl, &[Operand::E], 8, 2),
    Instruction::new(OpCode::Rl, &[Operand::H], 8, 2),
    Instruction::new(OpCode::Rl, &[Operand::L], 8, 2),
    Instruction::new(OpCode::Rl, &[Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Rl, &[Operand::A], 8, 2),
    Instruction::new(OpCode::Rr, &[Operand::B], 8, 2),
    Instruction::new(OpCode::Rr, &[Operand::C], 8, 2),
    Instruction::new(OpCode::Rr, &[Operand::D], 8, 2),
    Instruction::new(OpCode::Rr, &[Operand::E], 8, 2),
    Instruction::new(OpCode::Rr, &[Operand::H], 8, 2),
    Instruction::new(OpCode::Rr, &[Operand::L], 8, 2),
    Instruction::new(OpCode::Rr, &[Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Rr, &[Operand::A], 8, 2),
    Instruction::new(OpCode::Sla, &[Operand::B], 8, 2),
    Instruction::new(OpCode::Sla, &[Operand::C], 8, 2),
    Instruction::new(OpCode::Sla, &[Operand::D], 8, 2),
    Instruction::new(OpCode::Sla, &[Operand::E], 8, 2),
    Instruction::new(OpCode::Sla, &[Operand::H], 8, 2),
    Instruction::new(OpCode::Sla, &[Operand::L], 8, 2),
    Instruction::new(OpCode::Sla, &[Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Sla, &[Operand::A], 8, 2),
    Instruction::new(OpCode::Sra, &[Operand::B], 8, 2),
    Instruction::new(OpCode::Sra, &[Operand::C], 8, 2),
    Instruction::new(OpCode::Sra, &[Operand::D], 8, 2),
    Instruction::new(OpCode::Sra, &[Operand::E], 8, 2),
    Instruction::new(OpCode::Sra, &[Operand::H], 8, 2),
    Instruction::new(OpCode::Sra, &[Operand::L], 8, 2),
    Instruction::new(OpCode::Sra, &[Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Sra, &[Operand::A], 8, 2),
    Instruction::new(OpCode::Swap, &[Operand::B], 8, 2),
    Instruction::new(OpCode::Swap, &[Operand::C], 8, 2),
    Instruction::new(OpCode::Swap, &[Operand::D], 8, 2),
    Instruction::new(OpCode::Swap, &[Operand::E], 8, 2),
    Instruction::new(OpCode::Swap, &[Operand::H], 8, 2),
    Instruction::new(OpCode::Swap, &[Operand::L], 8, 2),
    Instruction::new(OpCode::Swap, &[Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Swap, &[Operand::A], 8, 2),
    Instruction::new(OpCode::Srl, &[Operand::B], 8, 2),
    Instruction::new(OpCode::Srl, &[Operand::C], 8, 2),
    Instruction::new(OpCode::Srl, &[Operand::D], 8, 2),
    Instruction::new(OpCode::Srl, &[Operand::E], 8, 2),
    Instruction::new(OpCode::Srl, &[Operand::H], 8, 2),
    Instruction::new(OpCode::Srl, &[Operand::L], 8, 2),
    Instruction::new(OpCode::Srl, &[Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Srl, &[Operand::A], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x0), Operand::B], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x0), Operand::C], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x0), Operand::D], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x0), Operand::E], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x0), Operand::H], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x0), Operand::L], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x0), Operand::HLPointer], 12, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x0), Operand::A], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x1), Operand::B], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x1), Operand::C], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x1), Operand::D], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x1), Operand::E], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x1), Operand::H], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x1), Operand::L], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x1), Operand::HLPointer], 12, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x1), Operand::A], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x2), Operand::B], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x2), Operand::C], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x2), Operand::D], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x2), Operand::E], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x2), Operand::H], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x2), Operand::L], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x2), Operand::HLPointer], 12, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x2), Operand::A], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x3), Operand::B], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x3), Operand::C], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x3), Operand::D], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x3), Operand::E], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x3), Operand::H], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x3), Operand::L], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x3), Operand::HLPointer], 12, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x3), Operand::A], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x4), Operand::B], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x4), Operand::C], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x4), Operand::D], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x4), Operand::E], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x4), Operand::H], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x4), Operand::L], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x4), Operand::HLPointer], 12, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x4), Operand::A], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x5), Operand::B], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x5), Operand::C], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x5), Operand::D], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x5), Operand::E], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x5), Operand::H], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x5), Operand::L], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x5), Operand::HLPointer], 12, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x5), Operand::A], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x6), Operand::B], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x6), Operand::C], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x6), Operand::D], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x6), Operand::E], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x6), Operand::H], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x6), Operand::L], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x6), Operand::HLPointer], 12, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x6), Operand::A], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x7), Operand::B], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x7), Operand::C], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x7), Operand::D], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x7), Operand::E], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x7), Operand::H], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x7), Operand::L], 8, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x7), Operand::HLPointer], 12, 2),
    Instruction::new(OpCode::Bit, &[Operand::Immediate(0x7), Operand::A], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x0), Operand::B], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x0), Operand::C], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x0), Operand::D], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x0), Operand::E], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x0), Operand::H], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x0), Operand::L], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x0), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x0), Operand::A], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x1), Operand::B], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x1), Operand::C], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x1), Operand::D], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x1), Operand::E], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x1), Operand::H], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x1), Operand::L], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x1), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x1), Operand::A], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x2), Operand::B], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x2), Operand::C], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x2), Operand::D], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x2), Operand::E], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x2), Operand::H], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x2), Operand::L], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x2), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x2), Operand::A], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x3), Operand::B], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x3), Operand::C], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x3), Operand::D], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x3), Operand::E], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x3), Operand::H], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x3), Operand::L], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x3), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x3), Operand::A], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x4), Operand::B], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x4), Operand::C], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x4), Operand::D], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x4), Operand::E], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x4), Operand::H], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x4), Operand::L], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x4), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x4), Operand::A], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x5), Operand::B], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x5), Operand::C], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x5), Operand::D], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x5), Operand::E], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x5), Operand::H], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x5), Operand::L], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x5), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x5), Operand::A], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x6), Operand::B], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x6), Operand::C], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x6), Operand::D], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x6), Operand::E], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x6), Operand::H], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x6), Operand::L], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x6), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x6), Operand::A], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x7), Operand::B], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x7), Operand::C], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x7), Operand::D], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x7), Operand::E], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x7), Operand::H], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x7), Operand::L], 8, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x7), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Res, &[Operand::Immediate(0x7), Operand::A], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x0), Operand::B], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x0), Operand::C], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x0), Operand::D], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x0), Operand::E], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x0), Operand::H], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x0), Operand::L], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x0), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x0), Operand::A], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x1), Operand::B], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x1), Operand::C], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x1), Operand::D], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x1), Operand::E], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x1), Operand::H], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x1), Operand::L], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x1), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x1), Operand::A], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x2), Operand::B], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x2), Operand::C], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x2), Operand::D], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x2), Operand::E], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x2), Operand::H], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x2), Operand::L], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x2), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x2), Operand::A], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x3), Operand::B], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x3), Operand::C], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x3), Operand::D], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x3), Operand::E], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x3), Operand::H], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x3), Operand::L], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x3), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x3), Operand::A], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x4), Operand::B], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x4), Operand::C], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x4), Operand::D], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x4), Operand::E], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x4), Operand::H], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x4), Operand::L], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x4), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x4), Operand::A], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x5), Operand::B], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x5), Operand::C], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x5), Operand::D], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x5), Operand::E], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x5), Operand::H], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x5), Operand::L], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x5), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x5), Operand::A], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x6), Operand::B], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x6), Operand::C], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x6), Operand::D], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x6), Operand::E], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x6), Operand::H], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x6), Operand::L], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x6), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x6), Operand::A], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x7), Operand::B], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x7), Operand::C], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x7), Operand::D], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x7), Operand::E], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x7), Operand::H], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x7), Operand::L], 8, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x7), Operand::HLPointer], 16, 2),
    Instruction::new(OpCode::Set, &[Operand::Immediate(0x7), Operand::A], 8, 2),
];
